/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.luence.app;

import org.apache.lucene.analysis.standard.StandardAnalyzer;
import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() throws IOException {
        StandardAnalyzer analyzer = new StandardAnalyzer();
        assertNotNull("index shouldn't be null", App.index(analyzer));
    }
}
